# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wikilength.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10wikilength.proto\x12\nwikilength\"?\n\rLengthRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04url1\x18\x02 \x01(\t\x12\x0c\n\x04url2\x18\x03 \x01(\t\"\x9c\x01\n\x0eLengthResponse\x12\x36\n\x06status\x18\x01 \x01(\x0e\x32&.wikilength.LengthResponse.QueryStatus\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\"-\n\x0bQueryStatus\x12\x0b\n\x07PENDING\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\x06\n\x02OK\x10\x02\x32X\n\nWikiLength\x12J\n\x0f\x43\x61lculateLength\x12\x19.wikilength.LengthRequest\x1a\x1a.wikilength.LengthResponse\"\x00\x62\x06proto3')



_LENGTHREQUEST = DESCRIPTOR.message_types_by_name['LengthRequest']
_LENGTHRESPONSE = DESCRIPTOR.message_types_by_name['LengthResponse']
_LENGTHRESPONSE_QUERYSTATUS = _LENGTHRESPONSE.enum_types_by_name['QueryStatus']
LengthRequest = _reflection.GeneratedProtocolMessageType('LengthRequest', (_message.Message,), {
  'DESCRIPTOR' : _LENGTHREQUEST,
  '__module__' : 'wikilength_pb2'
  # @@protoc_insertion_point(class_scope:wikilength.LengthRequest)
  })
_sym_db.RegisterMessage(LengthRequest)

LengthResponse = _reflection.GeneratedProtocolMessageType('LengthResponse', (_message.Message,), {
  'DESCRIPTOR' : _LENGTHRESPONSE,
  '__module__' : 'wikilength_pb2'
  # @@protoc_insertion_point(class_scope:wikilength.LengthResponse)
  })
_sym_db.RegisterMessage(LengthResponse)

_WIKILENGTH = DESCRIPTOR.services_by_name['WikiLength']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LENGTHREQUEST._serialized_start=32
  _LENGTHREQUEST._serialized_end=95
  _LENGTHRESPONSE._serialized_start=98
  _LENGTHRESPONSE._serialized_end=254
  _LENGTHRESPONSE_QUERYSTATUS._serialized_start=209
  _LENGTHRESPONSE_QUERYSTATUS._serialized_end=254
  _WIKILENGTH._serialized_start=256
  _WIKILENGTH._serialized_end=344
# @@protoc_insertion_point(module_scope)
