# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import wikilength_pb2 as wikilength__pb2


class WikiLengthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateLength = channel.unary_unary(
                '/wikilength.WikiLength/CalculateLength',
                request_serializer=wikilength__pb2.LengthRequest.SerializeToString,
                response_deserializer=wikilength__pb2.LengthResponse.FromString,
                )


class WikiLengthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateLength(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WikiLengthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateLength': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateLength,
                    request_deserializer=wikilength__pb2.LengthRequest.FromString,
                    response_serializer=wikilength__pb2.LengthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wikilength.WikiLength', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WikiLength(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateLength(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wikilength.WikiLength/CalculateLength',
            wikilength__pb2.LengthRequest.SerializeToString,
            wikilength__pb2.LengthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
